import { useEffect, useMemo, useRef } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { useUpdateEmployee, useRoles, type Employee, type LifecycleStage } from '@empla/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { buildPersonalityPresets } from './constants';

const editSchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters').max(200),
  email: z.string().email('Invalid email address'),
  lifecycleStage: z.enum(['shadow', 'supervised', 'autonomous'] as const),
  capabilities: z.string(),
  roleDescription: z.string().optional(),
  personalityPreset: z.string().optional(),
});

type EditFormData = z.infer<typeof editSchema>;

const lifecycleStages: { value: LifecycleStage; label: string }[] = [
  { value: 'shadow', label: 'Shadow' },
  { value: 'supervised', label: 'Supervised' },
  { value: 'autonomous', label: 'Autonomous' },
];

interface EmployeeEditDialogProps {
  employee: Employee;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function EmployeeEditDialog({ employee, open, onOpenChange }: EmployeeEditDialogProps) {
  const updateEmployee = useUpdateEmployee();
  const { data: rolesData, isLoading: rolesLoading } = useRoles();
  const apiRoles = rolesData?.roles ?? [];
  const personalityPresets = useMemo(() => buildPersonalityPresets(apiRoles), [apiRoles]);

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    reset,
    formState: { errors },
  } = useForm<EditFormData>({
    resolver: zodResolver(editSchema),
    defaultValues: {
      name: employee.name,
      email: employee.email,
      lifecycleStage: employee.lifecycleStage,
      capabilities: employee.capabilities.join(', '),
      roleDescription: (employee.config as Record<string, unknown>)?.role_description as string ?? '',
      personalityPreset: employee.personality?.preset as string ?? 'default',
    },
  });

  const prevOpenRef = useRef(false);
  useEffect(() => {
    if (open && !prevOpenRef.current) {
      reset({
        name: employee.name,
        email: employee.email,
        lifecycleStage: employee.lifecycleStage,
        capabilities: employee.capabilities.join(', '),
        roleDescription: (employee.config as Record<string, unknown>)?.role_description as string ?? '',
        personalityPreset: employee.personality?.preset as string ?? 'default',
      });
    }
    prevOpenRef.current = open;
  }, [open, employee, reset]);

  const selectedStage = watch('lifecycleStage');

  const onSubmit = async (data: EditFormData) => {
    const capabilities = data.capabilities
      .split(',')
      .map((c) => c.trim())
      .filter(Boolean);

    const config: Record<string, unknown> = {
      ...((employee.config as Record<string, unknown>) ?? {}),
    };
    const trimmedDescription = data.roleDescription?.trim();
    if (trimmedDescription) {
      config.role_description = trimmedDescription;
    } else {
      delete config.role_description;
    }

    // Custom employees (role='custom') have numeric slider personality
    // objects generated by the LLM, not preset strings. If the existing
    // personality is slider-shaped (has 'openness' key, no 'preset' key),
    // pass it through unchanged so an innocent name/email edit doesn't
    // silently reset personality to defaults.
    const existingPersonality = (employee.personality ?? {}) as Record<string, unknown>;
    const isCustomPersonality = 'openness' in existingPersonality && !('preset' in existingPersonality);
    const personality: Record<string, unknown> = isCustomPersonality
      ? existingPersonality
      : data.personalityPreset && data.personalityPreset !== 'default'
        ? { preset: data.personalityPreset }
        : {};

    try {
      await updateEmployee.mutateAsync({
        id: employee.id,
        data: {
          name: data.name,
          email: data.email,
          lifecycleStage: data.lifecycleStage,
          capabilities,
          config,
          personality,
        },
      });

      toast.success('Employee updated', {
        description: `${data.name} has been updated`,
      });
      onOpenChange(false);
    } catch (error) {
      toast.error('Failed to update employee', {
        description: error instanceof Error ? error.message : 'Please try again',
      });
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[480px]">
        <DialogHeader>
          <DialogTitle className="font-display">Edit Employee</DialogTitle>
          <DialogDescription>
            Update {employee.name}'s details
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          {/* Name */}
          <div className="space-y-2">
            <Label htmlFor="edit-name">Name</Label>
            <Input
              id="edit-name"
              className="bg-background/50"
              {...register('name')}
            />
            {errors.name && (
              <p className="text-sm text-destructive">{errors.name.message}</p>
            )}
          </div>

          {/* Email */}
          <div className="space-y-2">
            <Label htmlFor="edit-email">Email</Label>
            <Input
              id="edit-email"
              type="email"
              className="bg-background/50"
              {...register('email')}
            />
            {errors.email && (
              <p className="text-sm text-destructive">{errors.email.message}</p>
            )}
          </div>

          {/* Lifecycle Stage */}
          <div className="space-y-2">
            <Label htmlFor="lifecycleStage-select">Lifecycle Stage</Label>
            <Select
              value={selectedStage}
              onValueChange={(v: LifecycleStage) => setValue('lifecycleStage', v)}
            >
              <SelectTrigger id="lifecycleStage-select" className="bg-background/50">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {lifecycleStages.map((s) => (
                  <SelectItem key={s.value} value={s.value}>
                    {s.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Capabilities */}
          <div className="space-y-2">
            <Label htmlFor="edit-capabilities">Capabilities</Label>
            <Input
              id="edit-capabilities"
              placeholder="email, calendar, crm"
              className="bg-background/50"
              {...register('capabilities')}
            />
            <p className="text-xs text-muted-foreground">Comma-separated list</p>
          </div>

          {/* Role Description */}
          <div className="space-y-2">
            <Label htmlFor="edit-roleDescription">Role Description</Label>
            <Textarea
              id="edit-roleDescription"
              placeholder="Describe what this employee does..."
              className="bg-background/50 min-h-[80px]"
              {...register('roleDescription')}
            />
            <p className="text-xs text-muted-foreground">
              Included in every LLM prompt so the employee knows its purpose.
            </p>
          </div>

          {/* Personality Preset */}
          <div className="space-y-2">
            <Label htmlFor="edit-personalityPreset">Personality Preset</Label>
            <Select
              value={watch('personalityPreset') ?? 'default'}
              onValueChange={(value) => setValue('personalityPreset', value)}
              disabled={rolesLoading}
            >
              <SelectTrigger id="edit-personalityPreset" className="bg-background/50">
                <SelectValue placeholder={rolesLoading ? 'Loading…' : undefined} />
              </SelectTrigger>
              <SelectContent>
                {personalityPresets.map((preset) => (
                  <SelectItem key={preset.value} value={preset.value}>
                    {preset.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={updateEmployee.isPending}>
              {updateEmployee.isPending ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Saving...
                </>
              ) : (
                'Save Changes'
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
