"""
Base Capability Abstraction

Defines the core interface and models for all capabilities.
"""

from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
from uuid import UUID
from enum import Enum
from pydantic import BaseModel, Field
import logging

logger = logging.getLogger(__name__)


class CapabilityType(str, Enum):
    """
    Types of capabilities available to employees.

    Each capability type corresponds to a specific way employees
    can interact with the external world.
    """

    EMAIL = "email"
    CALENDAR = "calendar"
    MESSAGING = "messaging"
    BROWSER = "browser"
    DOCUMENT = "document"
    CRM = "crm"
    VOICE = "voice"
    COMPUTER_USE = "computer_use"


class CapabilityConfig(BaseModel):
    """
    Base configuration for all capabilities.

    Each capability extends this with capability-specific configuration.
    """

    enabled: bool = True
    """Whether this capability is enabled"""

    rate_limit: Optional[int] = None
    """Max operations per minute (None = unlimited)"""

    retry_policy: Dict[str, Any] = Field(
        default={"max_retries": 3, "backoff": "exponential"}
    )
    """Retry policy for failed operations"""

    timeout_seconds: int = 30
    """Operation timeout in seconds"""

    class Config:
        extra = "allow"  # Allow capability-specific config


class Observation(BaseModel):
    """
    Single observation from a capability.

    Observations are generated during perception and passed to the
    BDI system for reasoning.
    """

    source: str
    """Which capability generated this observation"""

    type: str
    """Type of observation (e.g., 'new_email', 'calendar_event')"""

    timestamp: datetime
    """When this observation was made"""

    priority: int = Field(ge=1, le=10, default=5)
    """Priority 1-10, higher = more important"""

    data: Dict[str, Any]
    """Observation-specific data"""

    requires_action: bool = False
    """Should this trigger immediate action?"""

    class Config:
        json_schema_extra = {
            "example": {
                "source": "email",
                "type": "new_email",
                "timestamp": "2025-11-12T10:30:00Z",
                "priority": 8,
                "data": {
                    "email_id": "123",
                    "from": "customer@example.com",
                    "subject": "Urgent: Need help",
                },
                "requires_action": True,
            }
        }


class Action(BaseModel):
    """
    Action to be executed by a capability.

    Actions are generated by the BDI system during intention execution
    and passed to capabilities for execution.
    """

    capability: str
    """Which capability should execute this action"""

    operation: str
    """What operation to perform (capability-specific)"""

    parameters: Dict[str, Any]
    """Operation parameters"""

    priority: int = Field(ge=1, le=10, default=5)
    """Action priority 1-10"""

    deadline: Optional[datetime] = None
    """When this action must be completed by"""

    context: Dict[str, Any] = Field(default_factory=dict)
    """Additional context for execution"""

    class Config:
        json_schema_extra = {
            "example": {
                "capability": "email",
                "operation": "send_email",
                "parameters": {
                    "to": ["recipient@example.com"],
                    "subject": "Response to your inquiry",
                    "body": "Thank you for reaching out...",
                },
                "priority": 7,
                "context": {"thread_id": "thread-123"},
            }
        }


class ActionResult(BaseModel):
    """
    Result of executing an action.

    Returned by capabilities after action execution.
    """

    success: bool
    """Whether the action succeeded"""

    output: Optional[Any] = None
    """Action output (capability-specific)"""

    error: Optional[str] = None
    """Error message if failed"""

    metadata: Dict[str, Any] = Field(default_factory=dict)
    """Additional metadata (timing, cost, etc.)"""

    class Config:
        json_schema_extra = {
            "example": {
                "success": True,
                "output": {"email_id": "456", "sent_at": "2025-11-12T10:35:00Z"},
                "error": None,
                "metadata": {"duration_ms": 234, "provider": "microsoft_graph"},
            }
        }


class BaseCapability(ABC):
    """
    Base class for all capabilities.

    A capability is a discrete unit of functionality that provides:
    1. **Perception** - observe environment for changes/events
    2. **Action** - execute specific operations
    3. **State** - maintain capability-specific state

    Capabilities are:
    - **Tenant-scoped** - isolated per customer
    - **Employee-scoped** - per-employee configuration
    - **Observable** - comprehensive logging and metrics
    - **Testable** - mock implementations available

    Example:
        class MyCapability(BaseCapability):

            @property
            def capability_type(self) -> CapabilityType:
                return CapabilityType.EMAIL

            async def initialize(self) -> None:
                # Set up connections, auth, etc.
                pass

            async def perceive(self) -> List[Observation]:
                # Check for new events
                return [...]

            async def execute_action(self, action: Action) -> ActionResult:
                # Execute operation
                return ActionResult(success=True)
    """

    def __init__(
        self, tenant_id: UUID, employee_id: UUID, config: CapabilityConfig
    ):
        """
        Initialize the capability instance with tenant, employee, and configuration context.
        
        Parameters:
            tenant_id (UUID): Identifier of the tenant that owns the capability.
            employee_id (UUID): Identifier of the employee associated with the capability.
            config (CapabilityConfig): Configuration values controlling capability behavior.
        """
        self.tenant_id = tenant_id
        self.employee_id = employee_id
        self.config = config
        self._initialized = False

    @property
    @abstractmethod
    def capability_type(self) -> CapabilityType:
        """
        Identify this capability's category.
        
        Returns:
            The CapabilityType value that represents this capability's category.
        """
        pass

    @abstractmethod
    async def initialize(self) -> None:
        """
        Prepare the capability for use for the assigned employee.
        
        Performs startup work such as establishing connections and authentication. Called once when the capability is enabled; implementations should set self._initialized = True on successful completion.
        
        Raises:
            Exception: If initialization fails.
        """
        pass

    @abstractmethod
    async def perceive(self) -> List[Observation]:
        """
        Detects new events, changes, or triggers from the capability's environment and produces corresponding observations.
        
        Implementations should perform a single perception pass and return any observations discovered. If an error occurs, implementations must not raise; they should log the error and return an empty list.
        
        Returns:
            List[Observation]: Observations discovered during this perception pass; an empty list if nothing new or on error.
        """
        pass

    @abstractmethod
    async def execute_action(self, action: Action) -> ActionResult:
        """
        Execute the given action on the target capability.
        
        Implementations perform the requested operation and return an ActionResult describing success, any capability-specific output, and an error message when execution fails. Implementations should capture internal failures and surface them via the returned ActionResult rather than raising.
        
        Parameters:
            action (Action): The operation to perform, including target capability, operation name, and parameters.
        
        Returns:
            ActionResult: Outcome of executing the action — `success` is `true` when the operation completed successfully; `output` contains capability-specific result data; `error` contains a human-readable message when `success` is `false`.
        """
        pass

    async def shutdown(self) -> None:
        """
        Perform an orderly shutdown of the capability, releasing resources and flushing any in-memory state.
        
        Called when the capability is disabled or the associated employee is deactivated. Subclasses should override to implement concrete cleanup; the base implementation is a no-op.
        """
        pass

    def is_healthy(self) -> bool:
        """
        Indicates whether the capability has completed initialization successfully.
        
        Returns:
            `true` if initialization completed successfully, `false` otherwise.
        """
        return self._initialized

    def __repr__(self) -> str:
        """
        Return a concise string representation of the capability instance.
        
        Returns:
            str: A string containing the class name, `capability_type`, `employee_id`, and whether the instance is initialized.
        """
        return (
            f"{self.__class__.__name__}("
            f"type={self.capability_type}, "
            f"employee={self.employee_id}, "
            f"initialized={self._initialized})"
        )