"""
empla.runner.health - Minimal Health + Wake Server

Raw asyncio HTTP server for employee health checks and external wake triggers.
No external dependencies — uses asyncio.start_server with manual HTTP parsing.

Endpoints:
  GET  /health  — health check (used by EmployeeManager.get_health)
  POST /wake    — wake the employee loop with an event payload
"""

import asyncio
import contextlib
import hmac
import json
import logging
import os
import time
from collections import deque
from collections.abc import Callable
from typing import Any
from uuid import UUID

logger = logging.getLogger(__name__)

_MAX_PENDING_EVENTS = 100
_MAX_WAKE_BODY_BYTES = 65_536
_MAX_DESCRIPTION_CHARS = 500  # cap on MCP-supplied tool descriptions
_AUTH_HEADER = "x-runner-token"


def _redact(value: str | None) -> str | None:
    """
    Strip likely secrets and PII from a free-form error string before it
    leaves the runner. Catches the obvious shapes — tokens in URLs, bearer
    headers echoed in error bodies, email addresses, common API key
    prefixes. Not a security guarantee — defense in depth so the dashboard
    doesn't accidentally surface credentials when an integration faults.
    """
    if not value:
        return value
    import re as _re

    # bearer / authorization headers echoed back
    redacted = _re.sub(
        r"(?i)(authorization|bearer)\s*[:= ]\s*\S+",
        r"\1: [REDACTED]",
        value,
    )
    # query-string token / api_key / access_token / secret values
    redacted = _re.sub(
        r"(?i)([?&](?:token|api_key|access_token|secret|key)=)[^&\s]+",
        r"\1[REDACTED]",
        redacted,
    )
    # common API-key prefixes (sk-, pk-, xoxb-, ghp_, github_pat_, AIza...)
    redacted = _re.sub(
        r"\b(?:sk|pk|xoxb|xoxp|ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_\-]{16,}",
        "[REDACTED_KEY]",
        redacted,
    )
    redacted = _re.sub(r"\bAIza[A-Za-z0-9_\-]{32,}", "[REDACTED_KEY]", redacted)
    # email addresses
    redacted = _re.sub(
        r"[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}", "[REDACTED_EMAIL]", redacted
    )
    # cap length so a runaway error message can't bloat responses
    if len(redacted) > 500:
        redacted = redacted[:500] + "...[truncated]"
    return redacted


class HealthServer:
    """Minimal HTTP server for health checks and wake triggers.

    The wake endpoint accepts event payloads from the API server
    (proxied via EmployeeManager) and stores them until the execution
    loop drains them at the start of the next cycle.
    """

    def __init__(
        self,
        employee_id: UUID,
        port: int,
        wake_callback: Callable[[], None] | None = None,
        tool_router: Any = None,
        auth_token: str | None = None,
    ) -> None:
        self.employee_id = employee_id
        self.port = port
        self._start_time = time.monotonic()
        self._server: asyncio.Server | None = None
        self.cycle_count = 0  # TODO: wire to ProactiveExecutionLoop.cycle_count
        self._wake_callback = wake_callback
        self._pending_events: deque[dict[str, Any]] = deque(maxlen=_MAX_PENDING_EVENTS)
        # Optional: ToolRouter reference for /tools introspection (PR #80).
        # When None, the /tools endpoints return 503 (employee runner not
        # wired to expose tools).
        self._tool_router = tool_router
        # Shared secret required on all non-/health endpoints. Generated by
        # EmployeeManager and passed via env var EMPLA_RUNNER_TOKEN at
        # spawn. When None (e.g. dev/tests without the env var), auth is
        # disabled — keep the dev path frictionless.
        self._auth_token = (
            auth_token if auth_token is not None else os.environ.get("EMPLA_RUNNER_TOKEN")
        )

    async def start(self) -> None:
        """Start the health server."""
        self._start_time = time.monotonic()
        self._server = await asyncio.start_server(self._handle_request, "127.0.0.1", self.port)
        # Update port to actual bound port (useful when port=0 for ephemeral)
        sockets = self._server.sockets
        if sockets:
            self.port = sockets[0].getsockname()[1]
        logger.info(
            f"Health server listening on 127.0.0.1:{self.port}",
            extra={"employee_id": str(self.employee_id)},
        )

    async def stop(self) -> None:
        """Stop the health server."""
        if self._server:
            self._server.close()
            await self._server.wait_closed()
            self._server = None
            logger.info(
                "Health server stopped",
                extra={"employee_id": str(self.employee_id)},
            )

    def drain_events(self) -> list[dict[str, Any]]:
        """Return and clear all pending events.

        Called by the execution loop early in each cycle to collect
        events that arrived since the last drain. Safe in single-threaded
        asyncio (no preemption between the swap and reassignment).
        """
        events = list(self._pending_events)
        self._pending_events.clear()
        return events

    async def _handle_request(
        self,
        reader: asyncio.StreamReader,
        writer: asyncio.StreamWriter,
    ) -> None:
        """Handle a single HTTP request."""
        try:
            request_line = await asyncio.wait_for(reader.readline(), timeout=5.0)
            request_str = request_line.decode("utf-8", errors="replace").strip()

            # Parse headers — we need Content-Length for POST bodies and
            # X-Runner-Token for auth-gated endpoints.
            content_length = 0
            received_token: str | None = None
            while True:
                line = await asyncio.wait_for(reader.readline(), timeout=5.0)
                if line in {b"\r\n", b"\n"} or not line:
                    break
                header_str = line.decode("utf-8", errors="replace").rstrip("\r\n")
                # Header name is case-insensitive but the value is case-
                # sensitive (matters for the base64url-encoded token).
                name, _, raw_value = header_str.partition(":")
                name = name.strip().lower()
                value = raw_value.strip()
                if name == "content-length":
                    with contextlib.suppress(ValueError):
                        content_length = int(value)
                elif name == _AUTH_HEADER:
                    received_token = value

            # Parse the request path once so dispatch can branch on exact
            # equality where it matters (avoids the prefix-matching footgun
            # where /tools/blocked could shadow /tools/blocked/health when a
            # tool happens to be named "blocked").
            parts = request_str.split(" ", 2)
            method = parts[0] if parts else ""
            raw_path = parts[1] if len(parts) > 1 else ""
            # Strip query string and fragment for path-only routing
            path = raw_path.split("?", 1)[0].split("#", 1)[0]

            # /health is unauthenticated (liveness probes need to work
            # without distributing the secret). Everything else requires
            # the X-Runner-Token header, validated with constant-time
            # comparison to avoid timing oracles.
            if method == "GET" and path == "/health":
                response_body, status_code = self._handle_health(), 200
            elif self._auth_token is not None and not (
                received_token is not None and hmac.compare_digest(received_token, self._auth_token)
            ):
                # Auth required but missing/wrong token. Constant-time
                # comparison to avoid token-length timing oracles.
                response_body, status_code = '{"error": "unauthorized"}', 401
            elif method == "POST" and path == "/wake":
                response_body, status_code = await self._handle_wake(reader, content_length)
            elif method == "GET" and path == "/tools":
                response_body, status_code = self._handle_tools_list()
            elif method == "GET" and path == "/tools/blocked":
                response_body, status_code = self._handle_tools_blocked()
            elif method == "GET" and path.startswith("/tools/") and path.endswith("/health"):
                # GET /tools/{name}/health — name may contain dots (email.send)
                response_body, status_code = self._handle_tool_health(path)
            else:
                response_body, status_code = '{"error": "not found"}', 404

            status_text = {
                200: "OK",
                400: "Bad Request",
                401: "Unauthorized",
                404: "Not Found",
                503: "Service Unavailable",
            }
            body_bytes = response_body.encode("utf-8")
            header = (
                f"HTTP/1.1 {status_code} {status_text.get(status_code, 'Error')}\r\n"
                "Content-Type: application/json\r\n"
                f"Content-Length: {len(body_bytes)}\r\n"
                "Connection: close\r\n"
                "\r\n"
            )

            writer.write(header.encode("utf-8") + body_bytes)
            await writer.drain()
        except TimeoutError:
            logger.debug(
                "Health server request timed out",
                extra={"employee_id": str(self.employee_id)},
            )
        except (ConnectionResetError, BrokenPipeError):
            logger.debug(
                "Health server client disconnected",
                extra={"employee_id": str(self.employee_id)},
            )
        except Exception:
            logger.warning(
                "Unexpected health server request error",
                exc_info=True,
                extra={"employee_id": str(self.employee_id)},
            )
        finally:
            writer.close()
            with contextlib.suppress(Exception):
                await writer.wait_closed()

    def _handle_health(self) -> str:
        """Build health check response body."""
        return json.dumps(
            {
                "status": "ok",
                "employee_id": str(self.employee_id),
                "uptime_seconds": round(time.monotonic() - self._start_time, 1),
                "cycle_count": self.cycle_count,
                "pending_events": len(self._pending_events),
            }
        )

    async def _handle_wake(
        self, reader: asyncio.StreamReader, content_length: int
    ) -> tuple[str, int]:
        """Handle POST /wake — store event and trigger loop wake."""
        if content_length < 0 or content_length > _MAX_WAKE_BODY_BYTES:
            return '{"error": "invalid or oversized payload"}', 400

        raw = b""
        if content_length > 0:
            raw = await asyncio.wait_for(reader.read(content_length), timeout=5.0)

        try:
            event = json.loads(raw) if raw else {}
        except (json.JSONDecodeError, ValueError):
            return '{"error": "invalid JSON"}', 400

        if not isinstance(event, dict):
            return '{"error": "payload must be a JSON object"}', 400

        if len(self._pending_events) >= _MAX_PENDING_EVENTS:
            dropped = self._pending_events.popleft()
            logger.warning(
                "Pending events queue full, dropping oldest event",
                extra={
                    "employee_id": str(self.employee_id),
                    "dropped_provider": dropped.get("provider", "unknown"),
                    "dropped_event_type": dropped.get("event_type", "unknown"),
                    "queue_size": _MAX_PENDING_EVENTS,
                },
            )

        self._pending_events.append(event)

        if self._wake_callback:
            try:
                self._wake_callback()
            except Exception:
                logger.warning(
                    "Wake callback failed, event stored but loop may not wake immediately",
                    exc_info=True,
                    extra={"employee_id": str(self.employee_id)},
                )

        logger.info(
            "Wake event received",
            extra={
                "employee_id": str(self.employee_id),
                "provider": event.get("provider", "unknown"),
                "event_type": event.get("event_type", "unknown"),
                "pending_count": len(self._pending_events),
            },
        )

        return json.dumps({"status": "accepted", "pending_events": len(self._pending_events)}), 200

    # =========================================================================
    # /tools, /tools/{name}/health, /tools/blocked  (PR #80)
    # =========================================================================

    def _handle_tools_list(self) -> tuple[str, int]:
        """Return the merged tool catalog this employee can execute."""
        if self._tool_router is None:
            return '{"error": "tools introspection not enabled for this runner"}', 503
        try:
            schemas = self._tool_router.get_all_tool_schemas(self.employee_id)
            integrations = self._tool_router.get_enabled_capabilities(self.employee_id)
            tools = [
                {
                    "name": s.get("name"),
                    # Cap description length — MCP-discovered tools provide
                    # attacker-influenceable text. The dashboard renders it
                    # as text (no innerHTML), but a 100KB description would
                    # bloat responses for no UX value.
                    "description": (s.get("description") or "")[:_MAX_DESCRIPTION_CHARS] or None,
                    "integration": (
                        s.get("name", "").split(".", 1)[0] if "." in s.get("name", "") else None
                    ),
                }
                for s in schemas
            ]
            # Embed per-integration health in the catalog response — avoids
            # the N+1 fan-out where the dashboard would call /tools/{name}/health
            # for every tool. Only one health entry per integration (not per
            # tool), keyed by the namespace prefix.
            unique_ints = {t["integration"] for t in tools if t["integration"]}
            health_map: dict[str, dict[str, Any]] = {}
            for integ in unique_ints:
                try:
                    h = self._tool_router.get_integration_health(integ)
                    if isinstance(h, dict) and "last_error" in h:
                        h = {**h, "last_error": _redact(h.get("last_error"))}
                    health_map[integ] = h
                except Exception:
                    # Don't fail the whole catalog if one integration's
                    # health read errors out — skip it.
                    logger.warning(
                        "Failed to read health for %s in catalog batching",
                        integ,
                        exc_info=True,
                    )
            return (
                json.dumps(
                    {
                        "items": tools,
                        "total": len(tools),
                        "integrations": integrations,
                        "health": health_map,
                    }
                ),
                200,
            )
        except Exception:
            logger.warning(
                "Failed to read tool catalog from tool_router",
                exc_info=True,
                extra={"employee_id": str(self.employee_id)},
            )
            return '{"error": "internal"}', 503

    def _handle_tool_health(self, path: str) -> tuple[str, int]:
        """Return integration health for the tool at ``path`` (/tools/{name}/health)."""
        if self._tool_router is None:
            return '{"error": "tools introspection not enabled for this runner"}', 503
        # Caller already verified the path matches /tools/{name}/health.
        name = path[len("/tools/") : -len("/health")]
        if not name:
            return '{"error": "missing tool name"}', 400
        # Tool names are namespaced as "integration.tool" — health is per-integration.
        integration = name.split(".", 1)[0] if "." in name else name
        try:
            health = self._tool_router.get_integration_health(integration)
            if isinstance(health, dict) and "last_error" in health:
                health = {**health, "last_error": _redact(health.get("last_error"))}
            return json.dumps(health), 200
        except Exception:
            logger.warning(
                "Failed to read integration health",
                exc_info=True,
                extra={"employee_id": str(self.employee_id), "integration": integration},
            )
            return '{"error": "internal"}', 503

    def _handle_tools_blocked(self) -> tuple[str, int]:
        """
        Return the trust-boundary blocks observed in the current cycle.

        Reads the trust audit log via ToolRouter._trust (private but stable
        within the runner process). Each entry is a TrustDecision with
        ``allowed=False``. The endpoint returns the most recent N entries.
        """
        if self._tool_router is None:
            return '{"error": "tools introspection not enabled for this runner"}', 503
        try:
            trust = getattr(self._tool_router, "_trust", None)
            if trust is None:
                # `stats` is required by the API's BlockedToolsResponse schema.
                # All TrustCycleStats fields have defaults, so an empty object
                # validates cleanly into a zeroed-out stats block.
                return (
                    '{"items": [], "total": 0, "stats": {}, "note": "trust boundary not active"}',
                    200,
                )
            audit = trust.get_audit_log()
            blocks = [
                {
                    "tool_name": d.tool_name,
                    "reason": d.reason,
                    "employee_role": d.employee_role,
                    "timestamp": d.timestamp,
                }
                for d in audit
                if not d.allowed
            ]
            stats = trust.get_cycle_stats()
            return json.dumps({"items": blocks, "total": len(blocks), "stats": stats}), 200
        except Exception:
            logger.warning(
                "Failed to read trust boundary audit log",
                exc_info=True,
                extra={"employee_id": str(self.employee_id)},
            )
            return '{"error": "internal"}', 503
